/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppReadLaterRouteImport } from './routes/app/read-later'
import { Route as AppOverviewRouteImport } from './routes/app/overview'
import { Route as ApiUploadthingRouteImport } from './routes/api/uploadthing'
import { Route as ApiSeedStoriesRouteImport } from './routes/api/seed-stories'
import { Route as MarketingContactRouteImport } from './routes/_marketing/contact'
import { Route as MarketingAboutRouteImport } from './routes/_marketing/about'
import { Route as AuthVerifyEmailRouteImport } from './routes/_auth/verify-email'
import { Route as AuthSignUpRouteImport } from './routes/_auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/_auth/sign-in'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AppStoriesIndexRouteImport } from './routes/app/stories/index'
import { Route as MarketingStoriesIndexRouteImport } from './routes/_marketing/stories/index'
import { Route as AppStoryNewRouteImport } from './routes/app/story/new'
import { Route as AppStoriesNewRouteImport } from './routes/app/stories/new'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as MarketingStoriesStoryIdRouteImport } from './routes/_marketing/stories/$storyId'
import { Route as AppStoriesStoryIdEditRouteImport } from './routes/app/stories/$storyId.edit'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/_marketing/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppReadLaterRoute = AppReadLaterRouteImport.update({
  id: '/read-later',
  path: '/read-later',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOverviewRoute = AppOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiUploadthingRoute = ApiUploadthingRouteImport.update({
  id: '/api/uploadthing',
  path: '/api/uploadthing',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSeedStoriesRoute = ApiSeedStoriesRouteImport.update({
  id: '/api/seed-stories',
  path: '/api/seed-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingContactRoute = MarketingContactRouteImport.update({
  id: '/_marketing/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/_marketing/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailRoute = AuthVerifyEmailRouteImport.update({
  id: '/_auth/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/_auth/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/_auth/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/_auth/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/_auth/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStoriesIndexRoute = AppStoriesIndexRouteImport.update({
  id: '/stories/',
  path: '/stories/',
  getParentRoute: () => AppRouteRoute,
} as any)
const MarketingStoriesIndexRoute = MarketingStoriesIndexRouteImport.update({
  id: '/_marketing/stories/',
  path: '/stories/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStoryNewRoute = AppStoryNewRouteImport.update({
  id: '/story/new',
  path: '/story/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppStoriesNewRoute = AppStoriesNewRouteImport.update({
  id: '/stories/new',
  path: '/stories/new',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingStoriesStoryIdRoute = MarketingStoriesStoryIdRouteImport.update({
  id: '/_marketing/stories/$storyId',
  path: '/stories/$storyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStoriesStoryIdEditRoute = AppStoriesStoryIdEditRouteImport.update({
  id: '/stories/$storyId/edit',
  path: '/stories/$storyId/edit',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/app': typeof AppRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/about': typeof MarketingAboutRoute
  '/contact': typeof MarketingContactRoute
  '/api/seed-stories': typeof ApiSeedStoriesRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/read-later': typeof AppReadLaterRoute
  '/app/settings': typeof AppSettingsRoute
  '/': typeof MarketingIndexRoute
  '/stories/$storyId': typeof MarketingStoriesStoryIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/stories/new': typeof AppStoriesNewRoute
  '/app/story/new': typeof AppStoryNewRoute
  '/stories/': typeof MarketingStoriesIndexRoute
  '/app/stories/': typeof AppStoriesIndexRoute
  '/app/stories/$storyId/edit': typeof AppStoriesStoryIdEditRoute
}
export interface FileRoutesByTo {
  '/app': typeof AppRouteRouteWithChildren
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/sign-in': typeof AuthSignInRoute
  '/sign-up': typeof AuthSignUpRoute
  '/verify-email': typeof AuthVerifyEmailRoute
  '/about': typeof MarketingAboutRoute
  '/contact': typeof MarketingContactRoute
  '/api/seed-stories': typeof ApiSeedStoriesRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/read-later': typeof AppReadLaterRoute
  '/app/settings': typeof AppSettingsRoute
  '/': typeof MarketingIndexRoute
  '/stories/$storyId': typeof MarketingStoriesStoryIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/stories/new': typeof AppStoriesNewRoute
  '/app/story/new': typeof AppStoryNewRoute
  '/stories': typeof MarketingStoriesIndexRoute
  '/app/stories': typeof AppStoriesIndexRoute
  '/app/stories/$storyId/edit': typeof AppStoriesStoryIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/app': typeof AppRouteRouteWithChildren
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_auth/sign-in': typeof AuthSignInRoute
  '/_auth/sign-up': typeof AuthSignUpRoute
  '/_auth/verify-email': typeof AuthVerifyEmailRoute
  '/_marketing/about': typeof MarketingAboutRoute
  '/_marketing/contact': typeof MarketingContactRoute
  '/api/seed-stories': typeof ApiSeedStoriesRoute
  '/api/uploadthing': typeof ApiUploadthingRoute
  '/app/overview': typeof AppOverviewRoute
  '/app/read-later': typeof AppReadLaterRoute
  '/app/settings': typeof AppSettingsRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/_marketing/stories/$storyId': typeof MarketingStoriesStoryIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/app/stories/new': typeof AppStoriesNewRoute
  '/app/story/new': typeof AppStoryNewRoute
  '/_marketing/stories/': typeof MarketingStoriesIndexRoute
  '/app/stories/': typeof AppStoriesIndexRoute
  '/app/stories/$storyId/edit': typeof AppStoriesStoryIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/app'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/about'
    | '/contact'
    | '/api/seed-stories'
    | '/api/uploadthing'
    | '/app/overview'
    | '/app/read-later'
    | '/app/settings'
    | '/'
    | '/stories/$storyId'
    | '/api/auth/$'
    | '/app/stories/new'
    | '/app/story/new'
    | '/stories/'
    | '/app/stories/'
    | '/app/stories/$storyId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/app'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/verify-email'
    | '/about'
    | '/contact'
    | '/api/seed-stories'
    | '/api/uploadthing'
    | '/app/overview'
    | '/app/read-later'
    | '/app/settings'
    | '/'
    | '/stories/$storyId'
    | '/api/auth/$'
    | '/app/stories/new'
    | '/app/story/new'
    | '/stories'
    | '/app/stories'
    | '/app/stories/$storyId/edit'
  id:
    | '__root__'
    | '/app'
    | '/_auth/forgot-password'
    | '/_auth/reset-password'
    | '/_auth/sign-in'
    | '/_auth/sign-up'
    | '/_auth/verify-email'
    | '/_marketing/about'
    | '/_marketing/contact'
    | '/api/seed-stories'
    | '/api/uploadthing'
    | '/app/overview'
    | '/app/read-later'
    | '/app/settings'
    | '/_marketing/'
    | '/_marketing/stories/$storyId'
    | '/api/auth/$'
    | '/app/stories/new'
    | '/app/story/new'
    | '/_marketing/stories/'
    | '/app/stories/'
    | '/app/stories/$storyId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerifyEmailRoute: typeof AuthVerifyEmailRoute
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingContactRoute: typeof MarketingContactRoute
  ApiSeedStoriesRoute: typeof ApiSeedStoriesRoute
  ApiUploadthingRoute: typeof ApiUploadthingRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingStoriesStoryIdRoute: typeof MarketingStoriesStoryIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  MarketingStoriesIndexRoute: typeof MarketingStoriesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/read-later': {
      id: '/app/read-later'
      path: '/read-later'
      fullPath: '/app/read-later'
      preLoaderRoute: typeof AppReadLaterRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/overview': {
      id: '/app/overview'
      path: '/overview'
      fullPath: '/app/overview'
      preLoaderRoute: typeof AppOverviewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/uploadthing': {
      id: '/api/uploadthing'
      path: '/api/uploadthing'
      fullPath: '/api/uploadthing'
      preLoaderRoute: typeof ApiUploadthingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/seed-stories': {
      id: '/api/seed-stories'
      path: '/api/seed-stories'
      fullPath: '/api/seed-stories'
      preLoaderRoute: typeof ApiSeedStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/contact': {
      id: '/_marketing/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof MarketingContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/verify-email': {
      id: '/_auth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof AuthVerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up': {
      id: '/_auth/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-in': {
      id: '/_auth/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/stories/': {
      id: '/app/stories/'
      path: '/stories'
      fullPath: '/app/stories/'
      preLoaderRoute: typeof AppStoriesIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_marketing/stories/': {
      id: '/_marketing/stories/'
      path: '/stories'
      fullPath: '/stories/'
      preLoaderRoute: typeof MarketingStoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/story/new': {
      id: '/app/story/new'
      path: '/story/new'
      fullPath: '/app/story/new'
      preLoaderRoute: typeof AppStoryNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/stories/new': {
      id: '/app/stories/new'
      path: '/stories/new'
      fullPath: '/app/stories/new'
      preLoaderRoute: typeof AppStoriesNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/stories/$storyId': {
      id: '/_marketing/stories/$storyId'
      path: '/stories/$storyId'
      fullPath: '/stories/$storyId'
      preLoaderRoute: typeof MarketingStoriesStoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/stories/$storyId/edit': {
      id: '/app/stories/$storyId/edit'
      path: '/stories/$storyId/edit'
      fullPath: '/app/stories/$storyId/edit'
      preLoaderRoute: typeof AppStoriesStoryIdEditRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppOverviewRoute: typeof AppOverviewRoute
  AppReadLaterRoute: typeof AppReadLaterRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStoriesNewRoute: typeof AppStoriesNewRoute
  AppStoryNewRoute: typeof AppStoryNewRoute
  AppStoriesIndexRoute: typeof AppStoriesIndexRoute
  AppStoriesStoryIdEditRoute: typeof AppStoriesStoryIdEditRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppOverviewRoute: AppOverviewRoute,
  AppReadLaterRoute: AppReadLaterRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStoriesNewRoute: AppStoriesNewRoute,
  AppStoryNewRoute: AppStoryNewRoute,
  AppStoriesIndexRoute: AppStoriesIndexRoute,
  AppStoriesStoryIdEditRoute: AppStoriesStoryIdEditRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerifyEmailRoute: AuthVerifyEmailRoute,
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingContactRoute: MarketingContactRoute,
  ApiSeedStoriesRoute: ApiSeedStoriesRoute,
  ApiUploadthingRoute: ApiUploadthingRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingStoriesStoryIdRoute: MarketingStoriesStoryIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  MarketingStoriesIndexRoute: MarketingStoriesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
